### ISSUE TITLE
Unable to start Docker Compose since PR #1 

### ISSUE THREAD

**Issue by markjhollands** [zowe/zowe-container-sample#5]
Since the merge of PR #1 I cannot start the stack with Docker Compose. Each of the ZLUX plugins report the following error (as an example):
```bash
zss-auth-plugin_1     | CONTRIBUTING.md
zss-auth-plugin_1     | LICENSE
zss-auth-plugin_1     | README.md
zss-auth-plugin_1     | lib/
zss-auth-plugin_1     | lib/zssAuth.js
zss-auth-plugin_1     | lib/safprofile.js
zss-auth-plugin_1     | package-lock.json
zss-auth-plugin_1     | package.json
zss-auth-plugin_1     | pluginDefinition.json
zss-auth-plugin_1     | test/
zss-auth-plugin_1     | test/safprofile-test.js
zss-auth-plugin_1     | zss-auth.ppf
zss-auth-plugin_1     | /dropins/bin/install-app.sh: cd: line 97: can't cd to /zlux-app-server/bin: No such file or directory
zss-auth-plugin_1     | Testing if node exists
zss-auth-plugin_1     | node: not found
zss-auth-plugin_1     | NodeJS not found or not requested, attempting fallback plugin install behavior
zss-auth-plugin_1     | Found plugin=org.zowe.zlux.auth.zss
zss-auth-plugin_1     | Ended with rc=1
zss-auth-plugin_1     | /dropins/bin/install-app.sh: line 118: can't create /workspace/app-server/plugins/org.zowe.zlux.auth.zss.json: nonexistent directory
zowe-container-sample_zss-auth-plugin_1 exited with code 0
```

I do not understand how the `/dropins/bin/install-app.sh` file persists from the ZLUX App Server build, but following it's execution there seems to be a number of issues:
* The `/zlux-app-server/bin` directory does not exist, which is understandable as it is in another container and is meant to refer to `/app/zowe-core/zlux-app-server/bin`?
* The base image for all the plugins is `busybox` not node, so it will not be able to find the `node` executable

I'm not sure how this is meant to work, but the `install-app.sh` script does not seem to work.

**Comment by markjhollands** [comment]
@NakulManchanda - any ideas?

**Comment by NakulManchanda** [comment]
Hi, can try again locally
[install-app.sh](https://github.com/zowe/zlux-app-server/blob/staging/bin/install-app.sh) needs ‘node’ installed

seems like we are hitting no node path during your run.

installNojs - function in script
which seems to be going to non existent path

for some reason i didnt hit that path

**Comment by NakulManchanda** [comment]
hi @markjhollands 

Created https://github.com/zowe/zowe-container-sample/pull/6 to resolve this issue.
Added `depends_on` in docker-compose to control the order, so plugins get copied to shared volume first.
And **removed** `install-app.sh` from plugins dockerbuild files, as we have no node in busybox, which is a dependency if we use that script.

But problem i am trying to solve is when to call [script](https://github.com/NakulManchanda/zowe-container-sample/blob/zlux-plugin-dependencies/build/zlux/pluginInstall.sh), its responsible for installing plugins.

When we build zlux docker before plugins or alone, we don't have any plugins folders copied to shared volume.

**Comment by markjhollands** [comment]
Verified that PR #6 fixes the issue. Closing.
